// <auto-generated />
namespace GoMentor.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_UserRoles_to_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_UserRoles_to_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201712122154143_Added_UserRoles_to_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
